import { useState, type FormEvent } from 'react';
import { Alert, Box, Button, InputAdornment, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { request, type Aparelho, type Cliente } from './api';
import { EmptyState, Icon, SectionHeader } from './ui';

export function CustomersPage({ token, clients, onRefresh }: { token: string; clients: Cliente[]; onRefresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState('');
  const filtered = clients.filter(x => `${x.nome} ${x.telefone} ${x.email ?? ''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  async function save(event: FormEvent) { event.preventDefault(); try { await request('/api/clientes', token, 'POST', { nome: name, telefone: phone, email }); await onRefresh(); setName(''); setPhone(''); setEmail(''); setOpen(false); setError(''); } catch (error) { setError(String(error)); } }
  return <>
    <SectionHeader eyebrow="Cadastros" title="Clientes" description="Encontre contatos rapidamente e mantenha o histórico organizado." action={<Button variant="contained" startIcon={<Icon name="plus" size={17}/>} onClick={() => setOpen(!open)}>{open ? 'Fechar cadastro' : 'Novo cliente'}</Button>} />
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    {open && <Paper component="form" onSubmit={save} sx={{ p: { xs: 2.5, sm: 3 }, mb: 3 }}><Typography variant="h6" sx={{ mb: .5 }}>Adicionar cliente</Typography><Typography color="text.secondary" sx={{ fontSize: 13, mb: 2.5 }}>Dados essenciais para acompanhar a OS e falar com o cliente.</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' }, gap: 2 }}><TextField label="Nome completo" required value={name} onChange={e => setName(e.target.value)}/><TextField label="Telefone / WhatsApp" required value={phone} onChange={e => setPhone(e.target.value)}/><TextField label="E-mail" type="email" value={email} onChange={e => setEmail(e.target.value)} sx={{ gridColumn: { md: 'span 2' } }}/></Box><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 2.5 }}><Button onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" variant="contained">Salvar cliente</Button></Stack></Paper>}
    <Paper sx={{ p: 2.5, mb: 2.5 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h6">Lista de clientes</Typography><Typography color="text.secondary" sx={{ fontSize: 12.5 }}>{clients.length} {clients.length === 1 ? 'cliente carregado' : 'clientes carregados'}</Typography></Box><TextField size="small" placeholder="Buscar por nome, telefone ou e-mail" value={search} onChange={e => setSearch(e.target.value)} sx={{ width: { xs: '100%', sm: 320 } }} InputProps={{ startAdornment: <InputAdornment position="start"><Icon name="search" size={17}/></InputAdornment> }}/></Stack></Paper>
    {filtered.length === 0 ? <EmptyState icon="users" title={search ? 'Nenhum cliente encontrado' : 'Comece pelos seus clientes'} description={search ? 'Tente outra busca ou limpe o campo acima.' : 'Cadastre o primeiro cliente para vincular aparelhos e ordens de serviço.'} action={search ? undefined : { label: 'Novo cliente', onClick: () => setOpen(true) }} /> : <Paper sx={{ overflow: 'hidden' }}>{filtered.map((x, i) => <Stack key={x.id} direction="row" alignItems="center" spacing={2} sx={{ px: { xs: 2, sm: 3 }, py: 2, borderBottom: i < filtered.length - 1 ? '1px solid #edf0f1' : 0 }}><Box sx={{ width: 41, height: 41, borderRadius: '50%', bgcolor: '#e6f3f2', color: 'primary.main', display: 'grid', placeItems: 'center', fontWeight: 800, flexShrink: 0 }}>{x.nome.slice(0, 1).toUpperCase()}</Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontWeight: 730 }}>{x.nome}</Typography><Typography color="text.secondary" sx={{ fontSize: 12.5 }}>{x.telefone}{x.email ? ` · ${x.email}` : ''}</Typography></Box></Stack>)}</Paper>}
  </>;
}

export function DevicesPage({ token, devices, clients, onRefresh }: { token: string; devices: Aparelho[]; clients: Cliente[]; onRefresh: () => Promise<void> }) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const [clientId, setClientId] = useState(''); const [brand, setBrand] = useState(''); const [model, setModel] = useState(''); const [imei, setImei] = useState('');
  const filtered = devices.filter(x => `${x.marca} ${x.modelo} ${x.imei ?? ''} ${clients.find(c => c.id === x.clienteId)?.nome ?? ''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  async function save(event: FormEvent) { event.preventDefault(); try { await request('/api/aparelhos', token, 'POST', { clienteId: clientId, marca: brand, modelo: model, imei }); await onRefresh(); setBrand(''); setModel(''); setImei(''); setOpen(false); setError(''); } catch (error) { setError(String(error)); } }
  return <>
    <SectionHeader eyebrow="Cadastros" title="Aparelhos" description="Identifique os dispositivos e veja a quem cada um pertence." action={<Button variant="contained" startIcon={<Icon name="plus" size={17}/>} onClick={() => setOpen(!open)}>{open ? 'Fechar cadastro' : 'Novo aparelho'}</Button>} />
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    {open && <Paper component="form" onSubmit={save} sx={{ p: { xs: 2.5, sm: 3 }, mb: 3 }}><Typography variant="h6" sx={{ mb: .5 }}>Adicionar aparelho</Typography><Typography color="text.secondary" sx={{ fontSize: 13, mb: 2.5 }}>Vincule o dispositivo a um cliente antes de abrir a OS.</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' }, gap: 2 }}><TextField select label="Cliente" required value={clientId} onChange={e => setClientId(e.target.value)} sx={{ gridColumn: { md: 'span 2' } }}>{clients.map(x => <MenuItem key={x.id} value={x.id}>{x.nome}</MenuItem>)}</TextField><TextField label="Marca" required value={brand} onChange={e => setBrand(e.target.value)}/><TextField label="Modelo" required value={model} onChange={e => setModel(e.target.value)}/><TextField label="IMEI (opcional)" value={imei} onChange={e => setImei(e.target.value)} sx={{ gridColumn: { md: 'span 2' } }}/></Box><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 2.5 }}><Button onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" variant="contained">Salvar aparelho</Button></Stack></Paper>}
    <Paper sx={{ p: 2.5, mb: 2.5 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h6">Dispositivos cadastrados</Typography><Typography color="text.secondary" sx={{ fontSize: 12.5 }}>{devices.length} {devices.length === 1 ? 'aparelho cadastrado' : 'aparelhos cadastrados'}</Typography></Box><TextField size="small" placeholder="Buscar aparelho ou cliente" value={search} onChange={e => setSearch(e.target.value)} sx={{ width: { xs: '100%', sm: 320 } }} InputProps={{ startAdornment: <InputAdornment position="start"><Icon name="search" size={17}/></InputAdornment> }}/></Stack></Paper>
    {filtered.length === 0 ? <EmptyState icon="devices" title={search ? 'Nenhum aparelho encontrado' : 'Nenhum aparelho cadastrado'} description={search ? 'Tente outra busca ou limpe o campo acima.' : 'Cadastre o primeiro dispositivo para começar a acompanhar os reparos.'} action={search ? undefined : { label: 'Novo aparelho', onClick: () => setOpen(true) }} /> : <Paper sx={{ overflow: 'hidden' }}>{filtered.map((x, i) => <Stack key={x.id} direction="row" alignItems="center" spacing={2} sx={{ px: { xs: 2, sm: 3 }, py: 2, borderBottom: i < filtered.length - 1 ? '1px solid #edf0f1' : 0 }}><Box sx={{ width: 41, height: 41, borderRadius: 2, bgcolor: '#eaf1f7', color: '#4b80a5', display: 'grid', placeItems: 'center', flexShrink: 0 }}><Icon name="devices" size={21}/></Box><Box sx={{ minWidth: 0 }}><Typography sx={{ fontWeight: 730 }}>{x.marca} {x.modelo}</Typography><Typography color="text.secondary" sx={{ fontSize: 12.5 }}>{clients.find(c => c.id === x.clienteId)?.nome ?? 'Cliente'}{x.imei ? ` · IMEI ${x.imei}` : ''}</Typography></Box></Stack>)}</Paper>}
  </>;
}
